### ISSUE TITLE
global_phone_dbgen not generating the json file. 

### ISSUE THREAD

**Issue by johnpaulh** [sstephenson/global_phone#40] opened 2015-12-10 14:00 UTC
This commit is not showing up in either release 1.0.0 or 1.01.  Because of which Http 404 error is thrown from global_phone_dbgen >>  command.

https://github.com/sstephenson/global_phone/commit/159a43733247d9f0165d44c27eaf80d791cdc220

Can you tag a new release with the above commit.
Regards,
John

**Comment by Luminus** [comment] 2015-12-16 17:20
This issue still persists. 

Please help sort this out.

**Comment by eileencodes** [comment] 2015-12-16 18:57
The new gem hasn't been released yet, but the issue is fixed in master on the commit mentioned. https://github.com/sstephenson/global_phone/pull/36

**Closed as completed by eileencodes** 2015-12-16 18:57 UTC

**Comment by Luminus** [comment] 2015-12-17 12:28
Awesome stuff @eileencodes. Thanks.
